In [5]:
# creating an object of ndarray by using array()

In [6]:
# syntax:varname=numpy.array(object,dtype)

In [7]:
# converting int type value into ndarray
import numpy as np
a=10
print("val of a={}".format(a))
print("type of a={}".format(type(a)))
print("----------------------------------")
nda=np.array(a)
print("val of nda={}".format(nda))
print("type of nda={}".format(type(nda)))
print("------------------------------------")
print("dimension nda={}".format(nda.ndim))
print("shape of nda={}".format(nda.shape))
print("size of nad= ",nda.size)
print("data type of nda= ",nda.dtype)
print("item size of nda= ",nda.itemsize)

val of a=10
type of a=<class 'int'>
----------------------------------
val of nda=10
type of nda=<class 'numpy.ndarray'>
------------------------------------
dimension nda=0
shape of nda=()
size of nad=  1
data type of nda=  int32
item size of nda=  4


In [28]:
a=10.32
print("val of a={}".format(a))
print("type of a={}".format(type(a)))
print("--------------------------------------")
nda=np.array(a)
print("val of nda={}".format(nda))
print("type of nda={}".format(type(nda)))
print("--------------------------------------")
print("dimension of nda={}".format(nda.ndim))
print("shape of nda={}".format(nda.shape))
print("size of nda={}".format(nda.size))
print("datatype of nda={}".format(nda.dtype))
print("itemsize of nda={}".format(nda.itemsize))

val of a=10.32
type of a=<class 'float'>
--------------------------------------
val of nda=10.32
type of nda=<class 'numpy.ndarray'>
--------------------------------------
dimension of nda=0
shape of nda=()
size of nda=1
datatype of nda=float64
itemsize of nda=8


In [44]:
s="PYTHON"
print("val of s={}".format(s))
print("type of s={}".format(type(s)))
print("-----------------------------")
nd=np.array(s)
print("val of nd={}".format(nd))
print("type of nd={}".format(type(nd)))
print("------------------------------------")
print("dimension of nd={}".format(nd.ndim))
print("shape of nd={}".format(nd.shape))
print("size of nd={}".format(nd.size))
print("datatype of nd={}".format(nd.dtype))
print("itemsize of nd={}".format(nd.itemsize))

val of s=PYTHON
type of s=<class 'str'>
-----------------------------
val of nd=PYTHON
type of nd=<class 'numpy.ndarray'>
------------------------------------
dimension of nd=0
shape of nd=()
size of nd=1
datatype of nd=<U6
itemsize of nd=24


In [50]:
r=range(10)
for val in r:
    print(val,end=" ")

0 1 2 3 4 5 6 7 8 9 

In [74]:
r=range(10)
a=np.array(r)
print("val of a=",a)
print(type(a))
print("dimension of a={}".format(a.ndim))
print("shape of a=",a.shape)
print("size of a=",a.size)
print("datatype of a=",a.dtype)

val of a= [0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
dimension of a=1
shape of a= (10,)
size of a= 10
datatype of a= int32


In [89]:
r=range(1,11)
a1=np.array(r)
print("val of r=",a1)
print(type(a1))
print("dimension of a=",a1.ndim)
print("shape of a=",a1.shape)
print("size of a=",a1.size)
print("datatype of a=",a1.dtype)

val of r= [ 1  2  3  4  5  6  7  8  9 10]
<class 'numpy.ndarray'>
dimension of a= 1
shape of a= (10,)
size of a= 10
datatype of a= int32


In [91]:
r=range(0,11,2)
a2=np.array(r)
print("val of a2=",a2)
print(type(a2))
print("dimension of a2=",a2.ndim)
print("shape of a2=",a2.shape)
print("size of a2=",a2.size)
print("datatype of a2=",a2.dtype)

val of r= [ 0  2  4  6  8 10]
<class 'numpy.ndarray'>
dimension of a= 1
shape of a= (6,)
size of a= 6
datatype of a= int32


In [103]:
r=range(100,121,2)
a3=np.array(r,dtype=float)
print("val of a3=",a3)
print(type(a3))
print("dimension of a3=",a3.ndim)
print("shape of a3=",a3.shape)
print("size of a3=",a3.size)
print("datatype of a3=",a3.dtype)

val of a3= [100. 102. 104. 106. 108. 110. 112. 114. 116. 118. 120.]
<class 'numpy.ndarray'>
dimension of a3= 1
shape of a3= (11,)
size of a3= 11
datatype of a3= float64


In [107]:
r=range(0,21,5)
a4=np.array(r,dtype=bool)
print("val of a4=",a4)
print(type(a4))
print("dimension of a4=",a4.ndim)
print("shape of a4=",a4.shape)
print("size of a4=",a4.size)
print("datatype of a4=",a4.dtype)

val of a4= [False  True  True  True  True]
<class 'numpy.ndarray'>
dimension of a4= 1
shape of a4= (5,)
size of a4= 5
datatype of a4= bool


In [128]:
r=range(0,12)
a5=np.array(r)
print("content of a5=",a5)
print("dimension of a5=",a5.ndim)
print("-------------------------------")
# convert ndarray object into 2-D array----by using reshap()
a5=a5.reshape(3,4)
print("content os a5={}".format(a5))
print("dimension of a5=",a5.ndim)
print("shape of a5=",a5.shape)
print("size of a5=",a5.size)
print("datatype of a5=",a5.dtype)

content of a5= [ 0  1  2  3  4  5  6  7  8  9 10 11]
dimension of a5= 1
-------------------------------
content os a5=[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
dimension of a5= 2
shape of a5= (3, 4)
size of a5= 12
datatype of a5= int32


In [148]:
r=range(0,12)
a6=np.array(r)
print("content of a6")
print(a6)
print("dimension of a5=",a6.ndim)
print("-------------------------------")
# convert ndarray object into 3-D array----by using reshap()
a6=a6.reshape(2,3,2)
print("content of a6")
print(a6)
print("dimension of a6=",a6.ndim)
print("shape of a6=",a6.shape)
print("size of a6=",a6.size)
print("datatype of a6=",a6.dtype)

content of a6
[ 0  1  2  3  4  5  6  7  8  9 10 11]
dimension of a5= 1
-------------------------------
content of a6
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
dimension of a6= 3
shape of a6= (2, 3, 2)
size of a6= 12
datatype of a6= int32


In [152]:
r=range(0,12)
b=np.array(r)
print("--------------------------------------")
print("content of b=",b)
print("dimension of b=",b.ndim)
print("---------------------------------")
# convert ndarray object into 2-D array----by using shape attribute
b.shape=(6,2)
print("content of b")
print(b)
print("dimension of b=",b.ndim)
print("shape of b=",b.shape)
print("size of b=",b.size)
print("datatype of b=",b.dtype)

--------------------------------------
content of b= [ 0  1  2  3  4  5  6  7  8  9 10 11]
dimension of b= 1
----------------------------------------
content of b
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
dimension of b= 2
shape of b= (6, 2)
size of b= 12
datatype of b= int32


In [159]:
r=range(0,12)
b=np.array(r)
print("--------------------------------------")
print("content of b=",b)
print("dimension of b=",b.ndim)
print("----------------------------------------")
# convert ndarray object into 3-D array----by using shape attribute
b.shape=(2,2,3)
print("content of b")
print(b)
print("dimension of b=",b.ndim)
print("shape of b=",b.shape)
print("size of b=",b.size)
print("datatype of b=",b.dtype)

--------------------------------------
content of b= [ 0  1  2  3  4  5  6  7  8  9 10 11]
dimension of b= 1
----------------------------------------
content of b
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
dimension of b= 3
shape of b= (2, 2, 3)
size of b= 12
datatype of b= int32
