## array()

In [2]:
# creating an object of ndarray by using array()

In [3]:
# syntax=>varname=numpy.array(object,dtype)

In [4]:
lst=[10,20,30,40,50,60,70,80,90,15,25,35]
print("content of lst=",lst)
print("type of lst=",type(lst))

content of lst= [10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 25, 35]
type of lst= <class 'list'>


In [5]:
import numpy as np
a=np.array(lst)
print("content of a=",a)
print("type of a=",type(a))

content of a= [10 20 30 40 50 60 70 80 90 15 25 35]
type of a= <class 'numpy.ndarray'>


In [6]:
lst=[10,20,30,40,50,60,70,80,90,15,25,35]
print("content of lst=",lst)
print("type of lst=",type(lst))
print("---------------------------------")
a=np.array(lst,dtype=float)
print("content of a=",a)
print("type of a=",type(a))
print("datatype of a=",a.dtype)
print("dimension of a =",a.ndim)
print("shape of a=",a.shape)
print("size of a=",a.size)

content of lst= [10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 25, 35]
type of lst= <class 'list'>
---------------------------------
content of a= [10. 20. 30. 40. 50. 60. 70. 80. 90. 15. 25. 35.]
type of a= <class 'numpy.ndarray'>
datatype of a= float64
dimension of a = 1
shape of a= (12,)
size of a= 12


In [7]:
# reshape of ndarray to 3x4 by using the reshape function
a=a.reshape(3,4)
print("content of a\n")
print(a)
print("dimension of a=",a.ndim)
print("shape of a=",a.shape)

content of a

[[10. 20. 30. 40.]
 [50. 60. 70. 80.]
 [90. 15. 25. 35.]]
dimension of a= 2
shape of a= (3, 4)


In [8]:
# reshape of ndarray to 4X3 by using the shape attribute
a.shape=(4,3)
print("content of a \n",a)
print("dimension of a=",a.ndim)
print("shape of a=",a.shape)

content of a 
 [[10. 20. 30.]
 [40. 50. 60.]
 [70. 80. 90.]
 [15. 25. 35.]]
dimension of a= 2
shape of a= (4, 3)


In [9]:
# reshape of ndarray by using the shape attribute
a.shape=(2,3,2)
print("content of a \n",a)
print("dimension of a=",a.ndim)
print("shape of a=",a.shape)

content of a 
 [[[10. 20.]
  [30. 40.]
  [50. 60.]]

 [[70. 80.]
  [90. 15.]
  [25. 35.]]]
dimension of a= 3
shape of a= (2, 3, 2)


In [10]:
# flaten the ndarray get it into 1-D 
a.shape=(12,)
print("content of a")
print(a)

content of a
[10. 20. 30. 40. 50. 60. 70. 80. 90. 15. 25. 35.]


In [11]:
# converting ineer list object into ndarray
lst=[[10,20,30],[40,50,60],[70,80,90]]
print("content of lst=",lst)
print("type of lst=",type(lst))
a=np.array(lst)
print("content of a \n")
print(a)
print("dimension of a=",a.ndim)
print("shape of a=",a.shape)

content of lst= [[10, 20, 30], [40, 50, 60], [70, 80, 90]]
type of lst= <class 'list'>
content of a 

[[10 20 30]
 [40 50 60]
 [70 80 90]]
dimension of a= 2
shape of a= (3, 3)


In [12]:
# converting the inner tuple object into ndarray
tpl=([10,20,30],[40,50,60],[70,80,90])
print("content of a",tpl)
print("type of tpl=",type(tpl))
print("---------------------------")
a=np.array(tpl)
print("content of a \n",a)
print("dimension of a=",a.ndim)
print("shape of a=",a.shape)

content of a ([10, 20, 30], [40, 50, 60], [70, 80, 90])
type of tpl= <class 'tuple'>
---------------------------
content of a 
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
dimension of a= 2
shape of a= (3, 3)


In [13]:
# converting the tuple into ndarray object
tpl=([[10,20,30],[40,50,60],[70,80,90]],[[1,2,3],[4,5,6],[7,8,9]])
print("content of tpl=",tpl)
print("tpe of tpl=",type(tpl))
print("---------------------------")
a=np.array(tpl)

print("content of a\n",a)
print("type of a=",type(a))
print("dimension of a=",a.ndim)
print("shape of a=",a.shape)

content of tpl= ([[10, 20, 30], [40, 50, 60], [70, 80, 90]], [[1, 2, 3], [4, 5, 6], [7, 8, 9]])
tpe of tpl= <class 'tuple'>
---------------------------
content of a
 [[[10 20 30]
  [40 50 60]
  [70 80 90]]

 [[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]]
type of a= <class 'numpy.ndarray'>
dimension of a= 3
shape of a= (2, 3, 3)


In [14]:
# converting set object into ndarray object 
s={10,20,30,40,50,60}
print("content of s=",s)
print("type of s=",type(s))
print("---------------------")
a=np.array(s)
print("content of a=",a)
print("type of a=",type(a))
print("dimension of a=",a.ndim)
print("shape of a=",a.shape)
print("size of a=",a.size)
print("datatype of a=",a.dtype)

content of s= {50, 20, 40, 10, 60, 30}
type of s= <class 'set'>
---------------------
content of a= {50, 20, 40, 10, 60, 30}
type of a= <class 'numpy.ndarray'>
dimension of a= 0
shape of a= ()
size of a= 1
datatype of a= object


In [15]:
# converting dict object into ndarray object 
d={10:"mango",20:"apple",30:"banana"}
print("content of d=",d)
print("type of d=",type(d))
print("---------------------")
a=np.array(d)
print("content of a=",a)
print("type of a=",type(a))
print("dimension of a=",a.ndim)
print("shape of a=",a.shape)
print("size of a=",a.size)
print("datatype of a=",a.dtype)

content of d= {10: 'mango', 20: 'apple', 30: 'banana'}
type of d= <class 'dict'>
---------------------
content of a= {10: 'mango', 20: 'apple', 30: 'banana'}
type of a= <class 'numpy.ndarray'>
dimension of a= 0
shape of a= ()
size of a= 1
datatype of a= object


In [16]:
# misc points
s="PYTHON"
a=list(s)
print(a)
a=np.array(a)
print("content of a=",a)
print("type of a=",type(a))

['P', 'Y', 'T', 'H', 'O', 'N']
content of a= ['P' 'Y' 'T' 'H' 'O' 'N']
type of a= <class 'numpy.ndarray'>


In [17]:
s="PYTHON"
a=list(s)
print(a)
a=np.array(a)
print("content of a=",a)
print("------------------------")
a=a.reshape(2,3)
print("content of a\n",a)

['P', 'Y', 'T', 'H', 'O', 'N']
content of a= ['P' 'Y' 'T' 'H' 'O' 'N']
------------------------
content of a
 [['P' 'Y' 'T']
 ['H' 'O' 'N']]


In [18]:
s="""python is an oop lang
    python developed by the guido van rossum"""
print(s)
words=s.split()
len(words)

python is an oop lang
    python developed by the guido van rossum


12

In [19]:
s="""python is an oop lang
    python developed by the guido van rossum"""
print(s)
words=s.split()
a=np.array(words)
a=a.reshape(4,3)
print("content of a")
print(a)

python is an oop lang
    python developed by the guido van rossum
content of a
[['python' 'is' 'an']
 ['oop' 'lang' 'python']
 ['developed' 'by' 'the']
 ['guido' 'van' 'rossum']]


In [39]:
import numpy as np

In [41]:
a=np.arange(20)

In [43]:
print(a,type(a))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19] <class 'numpy.ndarray'>


In [47]:
a.shape=(10,2)

In [49]:
print("content of a")
print(a)

content of a
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


In [53]:
a=np.arange(10).reshape(2,5)
print("content of a")
print(a)

content of a
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [59]:
a=np.arange(2,20)
print("content of a ")
print(a,type(a))
print("datatype of a=",a.dtype)
print("dimension of a=",a.ndim)
print("shape of a=",a.shape)
print("size of a=",a.size)

content of a 
[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19] <class 'numpy.ndarray'>
type of a= int32
dimension of a= 1
shape of a= (18,)
size of a= 18


In [61]:
a=np.arange(0,100).reshape(10,10)
print("content of a \n",a)
print("dimension of a=",a.ndim)

content of a 
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
dimension of a= 2


## zeros()

In [66]:
import numpy as np
a=np.zeros(4)
print(a)

[0. 0. 0. 0.]


In [70]:
a=np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [74]:
a=np.zeros((5,5),int)
print(a)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [78]:
a=np.zeros((3,3,3),int)
print(a)
print("dimension of a=",a.ndim)

[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
dimension of a= 3
