## 19 th sep 

## eye()

In [6]:
# create an object of ndarray by using eye()

In [26]:
# varname=numpy.eye(N,M=None,K=0,dtype) here default dtypa is float and k is always defalut taken as 0

In [28]:
import numpy as np
a=np.eye(2)

In [30]:
print(a)

[[1. 0.]
 [0. 1.]]


In [32]:
a=np.eye(3,dtype=int)

In [34]:
print(a)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [36]:
a=np.eye(6,dtype=int)
print(a)

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]


In [38]:
a=np.eye(3,4,dtype=int)
print(a)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]


In [40]:
a=np.eye(2,3,dtype=int)
print(a)

[[1 0 0]
 [0 1 0]]


In [42]:
a=np.eye(3,6,dtype=int)
print(a)

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]]


In [44]:
a=np.eye(4,3,dtype=int)
print(a)

[[1 0 0]
 [0 1 0]
 [0 0 1]
 [0 0 0]]


In [46]:
a=np.eye(6,dtype=int)
print(a)

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]


In [48]:
a=np.eye(6,2,dtype=int)
print(a)

[[1 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]


In [50]:
a=np.eye(6,k=-1,dtype=int)
print(a)

[[0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]]


In [52]:
a=np.eye(6,k=-2,dtype=int)
print(a)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]]


In [54]:
a=np.eye(6,k=-5,dtype=int)
print(a)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [1 0 0 0 0 0]]


In [58]:
a=np.eye(6,k=-4,dtype=int)
print(a)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [0 1 0 0 0 0]]


In [62]:
a=np.eye(6,k=1,dtype=int)
print(a)

[[0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]
 [0 0 0 0 0 0]]


In [64]:
a=np.eye(6,k=4,dtype=int)
print(a)

[[0 0 0 0 1 0]
 [0 0 0 0 0 1]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [66]:
a=np.eye(6,k=5,dtype=int)
print(a)

[[0 0 0 0 0 1]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
