## hstack() and vstack()

In [3]:
# creating an object of ndarry by using hstack()

In [5]:
# syntax:varname=numpy.hstack((ndarrayobj1,ndarrayobj2))

In [7]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,8])
print(a)
print(b)

[1 2 3]
[4 5 8]


In [9]:
c=np.hstack((a,b))
print(c,type(c))

[1 2 3 4 5 8] <class 'numpy.ndarray'>


In [11]:
d=np.hstack((b,a))
print(d,type(d))

[4 5 8 1 2 3] <class 'numpy.ndarray'>


In [13]:
a=np.arange(3*3).reshape(3,3)
b=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(a,type(a))
print(b,type(b))

[[0 1 2]
 [3 4 5]
 [6 7 8]] <class 'numpy.ndarray'>
[[10 20 30]
 [40 50 60]
 [70 80 90]] <class 'numpy.ndarray'>


In [15]:
c=np.hstack((a,b))
print(c,type(c))

[[ 0  1  2 10 20 30]
 [ 3  4  5 40 50 60]
 [ 6  7  8 70 80 90]] <class 'numpy.ndarray'>


In [19]:
a=np.arange(3*4).reshape(3,4)
b=np.array([[10,20,30],[40,50,60],[70,80,90]])
print("A-matrix")
print(a)
print("B-matrix")
print(b)

A-matrix
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
B-matrix
[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [21]:
print("C-matrix")
c=np.hstack((a,b))
print(c,type(c))

C-matrix
[[ 0  1  2  3 10 20 30]
 [ 4  5  6  7 40 50 60]
 [ 8  9 10 11 70 80 90]] <class 'numpy.ndarray'>


In [23]:
print("D-matrix")
d=np.hstack((b,a))
print(d,type(d))

D-matrix
[[10 20 30  0  1  2  3]
 [40 50 60  4  5  6  7]
 [70 80 90  8  9 10 11]] <class 'numpy.ndarray'>


## vstack()

In [26]:
# creating the an object of ndarray by using the vstack()

In [28]:
# syntax: varname=numpy.vstack((numpyobj1,numpyobj2))

In [34]:
a=np.array(range(0,9)).reshape(3,3)
b=np.array(range(10,16)).reshape(2,3)
print("A-matrix")
print(a)
print("B-matrix")
print(b)

A-matrix
[[0 1 2]
 [3 4 5]
 [6 7 8]]
B-matrix
[[10 11 12]
 [13 14 15]]


In [36]:
print("C-matrix")
c=np.vstack((a,b))
print(c,type(c))

C-matrix
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [10 11 12]
 [13 14 15]] <class 'numpy.ndarray'>


In [38]:
print("D-matrix")
d=np.vstack((b,a))
print(d,type(d))

D-matrix
[[10 11 12]
 [13 14 15]
 [ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]] <class 'numpy.ndarray'>
