## iterating the elements by using loops

In [7]:
# itration 1-D array by using the for loop 

In [9]:
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90])
for i in a:
    print(i)

10
20
30
40
50
60
70
80
90


In [13]:
# by using the while loop
a=np.array([10,20,30,40,50,60,70,80,90])
r=0
while(r<len(a)):
    print(a[r])
    r=r+1

10
20
30
40
50
60
70
80
90


In [17]:
# by using the for loop on the 2-D Array object
a=np.array([10,20,30,40,50,60,70,80,90]).reshape(3,3)
print(a)
print("========================================")
for row in a:
    for col in row:
        print(col)

[[10 20 30]
 [40 50 60]
 [70 80 90]]
10
20
30
40
50
60
70
80
90


In [21]:
# by using the while loop on the 2-D Array object
a=np.array([10,20,30,40,50,60,70,80,90]).reshape(3,3)
r=0
while(r<len(a)):
    c=0
    while(c<len(a[r])):
        print(a[r,c])
        c=c+1
    else:
        r=r+1
    

10
20
30
40
50
60
70
80
90


In [25]:
# by using the for loop on the 3-D Array object
a=np.arange(2*3*3).reshape(2,3,3)
for matrix in a:
    for row in matrix:
        for col in row:
            print(col)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17


In [27]:
# by using the for loop on the 3-D Array object
a=np.arange(2*3*3).reshape(2,3,3)
m=0
while(m<len(a)):
    r=0
    while(r<len(a[m])):
        c=0
        while(c<len(a[m,r])):
            print(a[m,r,c])
            c+=1
        else:
            r+=1
    else:
        m=m+1

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17


## iterating the elements by using nditer()

In [32]:
# syntax: np.nditer()

In [34]:
# by using the nditer() on 1-D array object

In [36]:
a=np.array([10,20,30,40,50,60,70,80,90])
for val in np.nditer(a):
    print(val)

10
20
30
40
50
60
70
80
90


In [38]:
# by using the nditer() on 2-D array object
a=np.array([10,20,30,40,50,60,70,80,90]).reshape(3,3)
for val in np.nditer(a):
    print(val)

10
20
30
40
50
60
70
80
90


In [40]:
# by using the nditer() on 3-D array object
a=np.arange(2*3*3).reshape(2,3,3)
for val in np.nditer(a):
    print(val)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17


## iterating the elements by using the np.ndenumerate()

In [44]:
a=np.array([10,20,30,40,50,60,70,80,90])
for index,value in np.ndenumerate(a):
    print("{}-->{}".format(index,value))

(0,)-->10
(1,)-->20
(2,)-->30
(3,)-->40
(4,)-->50
(5,)-->60
(6,)-->70
(7,)-->80
(8,)-->90


In [46]:
a=np.array([10,20,30,40,50,60,70,80,90]).reshape(3,3)
for index,value in np.ndenumerate(a):
    print("{}-->{}".format(index,value))

(0, 0)-->10
(0, 1)-->20
(0, 2)-->30
(1, 0)-->40
(1, 1)-->50
(1, 2)-->60
(2, 0)-->70
(2, 1)-->80
(2, 2)-->90


In [48]:
a=np.array([10,20,30,40,50,60,70,80,90]).reshape(3,3)
for index,value in np.ndenumerate(a):
    print("row:{} column:{} value:{}".format(index[0],index[1],value))

row:0 column:0 value:10
row:0 column:1 value:20
row:0 column:2 value:30
row:1 column:0 value:40
row:1 column:1 value:50
row:1 column:2 value:60
row:2 column:0 value:70
row:2 column:1 value:80
row:2 column:2 value:90


In [50]:
a=np.array([10,20,30,40,50,60,70,80,90]).reshape(3,3)
for index,value in np.ndenumerate(a):
    print("row:{} column:{} value:{}".format(index[-2],index[-1],value))

row:0 column:0 value:10
row:0 column:1 value:20
row:0 column:2 value:30
row:1 column:0 value:40
row:1 column:1 value:50
row:1 column:2 value:60
row:2 column:0 value:70
row:2 column:1 value:80
row:2 column:2 value:90


In [56]:
a=np.array(range(10,100,5)).reshape(2,3,3)
for index,value in np.ndenumerate(a):
    print("{}-->{}".format(index,value))

(0, 0, 0)-->10
(0, 0, 1)-->15
(0, 0, 2)-->20
(0, 1, 0)-->25
(0, 1, 1)-->30
(0, 1, 2)-->35
(0, 2, 0)-->40
(0, 2, 1)-->45
(0, 2, 2)-->50
(1, 0, 0)-->55
(1, 0, 1)-->60
(1, 0, 2)-->65
(1, 1, 0)-->70
(1, 1, 1)-->75
(1, 1, 2)-->80
(1, 2, 0)-->85
(1, 2, 1)-->90
(1, 2, 2)-->95


In [58]:
a=np.array(range(10,100,5)).reshape(2,3,3)
for index,value in np.ndenumerate(a):
    print("matrix:{} row:{} column:{} value:{}".format(index[0],index[1],index[2],value))

matrix:0 row:0 column:0 value:10
matrix:0 row:0 column:1 value:15
matrix:0 row:0 column:2 value:20
matrix:0 row:1 column:0 value:25
matrix:0 row:1 column:1 value:30
matrix:0 row:1 column:2 value:35
matrix:0 row:2 column:0 value:40
matrix:0 row:2 column:1 value:45
matrix:0 row:2 column:2 value:50
matrix:1 row:0 column:0 value:55
matrix:1 row:0 column:1 value:60
matrix:1 row:0 column:2 value:65
matrix:1 row:1 column:0 value:70
matrix:1 row:1 column:1 value:75
matrix:1 row:1 column:2 value:80
matrix:1 row:2 column:0 value:85
matrix:1 row:2 column:1 value:90
matrix:1 row:2 column:2 value:95


In [60]:
a=np.array(range(10,100,5)).reshape(2,3,3)
for index,value in np.ndenumerate(a):
    print("matrix:{} row:{} column:{} value:{}".format(index[-3],index[-2],index[-1],value))

matrix:0 row:0 column:0 value:10
matrix:0 row:0 column:1 value:15
matrix:0 row:0 column:2 value:20
matrix:0 row:1 column:0 value:25
matrix:0 row:1 column:1 value:30
matrix:0 row:1 column:2 value:35
matrix:0 row:2 column:0 value:40
matrix:0 row:2 column:1 value:45
matrix:0 row:2 column:2 value:50
matrix:1 row:0 column:0 value:55
matrix:1 row:0 column:1 value:60
matrix:1 row:0 column:2 value:65
matrix:1 row:1 column:0 value:70
matrix:1 row:1 column:1 value:75
matrix:1 row:1 column:2 value:80
matrix:1 row:2 column:0 value:85
matrix:1 row:2 column:1 value:90
matrix:1 row:2 column:2 value:95


In [62]:
a=np.arange(16).reshape(2,2,2,2)
print("content of a")
print(a)

content of a
[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]]


In [64]:
for index,value in np.ndenumerate(a):
    print("{}-->{}".format(index,value))

(0, 0, 0, 0)-->0
(0, 0, 0, 1)-->1
(0, 0, 1, 0)-->2
(0, 0, 1, 1)-->3
(0, 1, 0, 0)-->4
(0, 1, 0, 1)-->5
(0, 1, 1, 0)-->6
(0, 1, 1, 1)-->7
(1, 0, 0, 0)-->8
(1, 0, 0, 1)-->9
(1, 0, 1, 0)-->10
(1, 0, 1, 1)-->11
(1, 1, 0, 0)-->12
(1, 1, 0, 1)-->13
(1, 1, 1, 0)-->14
(1, 1, 1, 1)-->15
