## slicing operations on 1-D array

In [3]:
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90])
print("content of a")
print(a)

content of a
[10 20 30 40 50 60 70 80 90]


In [5]:
a[0]

10

In [7]:
a[0:4]

array([10, 20, 30, 40])

In [9]:
a[0:len(a)-1]

array([10, 20, 30, 40, 50, 60, 70, 80])

In [11]:
a[0:len(a)]

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [13]:
a[0:5]

array([10, 20, 30, 40, 50])

In [15]:
a[4:0]

array([], dtype=int32)

In [17]:
a[0:10:1]

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [19]:
a[0:10:2]

array([10, 30, 50, 70, 90])

In [21]:
a[-1:-10]

array([], dtype=int32)

In [25]:
a[-1:-10:-1]

array([90, 80, 70, 60, 50, 40, 30, 20, 10])

In [27]:
a[:10]

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [29]:
a[0:]

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [31]:
a[:10]

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [33]:
print(a)

[10 20 30 40 50 60 70 80 90]


In [35]:
a[:]

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [37]:
a[::-1]

array([90, 80, 70, 60, 50, 40, 30, 20, 10])

In [41]:
print(a[::-2])

[90 70 50 30 10]


## slicing operations on 2-D Array

In [44]:
a=np.array([10,20,30,40,50,60,70,80,90]).reshape(3,3)
print("content of a")
print(a)

content of a
[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [46]:
print(a[0:3,0:1])

[[10]
 [40]
 [70]]


In [48]:
a[:,0:1]

array([[10],
       [40],
       [70]])

In [50]:
a[0:,0:1]

array([[10],
       [40],
       [70]])

In [52]:
a[:,:1]

array([[10],
       [40],
       [70]])

In [54]:
a[0:,:1]

array([[10],
       [40],
       [70]])

In [56]:
a[:3,:1]

array([[10],
       [40],
       [70]])

In [58]:
a[::,0:1]

array([[10],
       [40],
       [70]])

In [60]:
a[::,0:1:1]

array([[10],
       [40],
       [70]])

In [62]:
a[::1,:1:]

array([[10],
       [40],
       [70]])

In [64]:
print(a)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [68]:
a[-3:,-3:-2]

array([[10],
       [40],
       [70]])

In [72]:
a[-3::1,-3:-2:1]

array([[10],
       [40],
       [70]])

In [74]:
print(a)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [76]:
a[1:3:1,0:2:1]

array([[40, 50],
       [70, 80]])

In [78]:
a[1:,:2]

array([[40, 50],
       [70, 80]])

In [80]:
a[1::1,:2:1]

array([[40, 50],
       [70, 80]])

In [82]:
a[-2:,-3:-1]

array([[40, 50],
       [70, 80]])

In [84]:
a[-2::1,-3:-1:1]

array([[40, 50],
       [70, 80]])

In [86]:
a[1:,-3:-1:1]

array([[40, 50],
       [70, 80]])

In [88]:
a[0:2,1:3]

array([[20, 30],
       [50, 60]])

In [90]:
a[0:3:2,0:3]

array([[10, 20, 30],
       [70, 80, 90]])

In [92]:
a[::2,:]

array([[10, 20, 30],
       [70, 80, 90]])

In [94]:
a[::2,::]

array([[10, 20, 30],
       [70, 80, 90]])

In [96]:
a[0::2,0::1]

array([[10, 20, 30],
       [70, 80, 90]])

In [98]:
print(a)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [100]:
a[:,1:2]

array([[20],
       [50],
       [80]])

In [102]:
a[:,::2]

array([[10, 30],
       [40, 60],
       [70, 90]])

In [104]:
print(a)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [108]:
a[::2,::2] # all corner elements

array([[10, 30],
       [70, 90]])

In [110]:
a[0:3:2,0:3:2]

array([[10, 30],
       [70, 90]])

## slicing operation on N-D Array

In [1]:
# syntax:ndarrayobj[mat beg:mat end:mat step,row beg:row end:row step,col beg:col end:col step]

In [5]:
import numpy as np
a=np.random.randint(10,50,size=(3,3,3))
print("content of a")
print(a)

content of a
[[[20 46 14]
  [47 48 35]
  [13 37 26]]

 [[31 41 34]
  [38 16 42]
  [22 21 19]]

 [[26 45 23]
  [42 33 21]
  [34 12 45]]]


In [7]:
a[0:1,1:3,1:2]

array([[[48],
        [37]]])

In [9]:
a[:1,1:,1:2]

array([[[48],
        [37]]])

In [11]:
a[:1:1,1::1,1:2:1]

array([[[48],
        [37]]])

In [13]:
print(a)

[[[20 46 14]
  [47 48 35]
  [13 37 26]]

 [[31 41 34]
  [38 16 42]
  [22 21 19]]

 [[26 45 23]
  [42 33 21]
  [34 12 45]]]


In [15]:
a[-3:-2,-2:,-2:-1]

array([[[48],
        [37]]])

In [17]:
print(a)

[[[20 46 14]
  [47 48 35]
  [13 37 26]]

 [[31 41 34]
  [38 16 42]
  [22 21 19]]

 [[26 45 23]
  [42 33 21]
  [34 12 45]]]


In [19]:
a[:,2:,:]

array([[[13, 37, 26]],

       [[22, 21, 19]],

       [[34, 12, 45]]])

In [21]:
print(a)

[[[20 46 14]
  [47 48 35]
  [13 37 26]]

 [[31 41 34]
  [38 16 42]
  [22 21 19]]

 [[26 45 23]
  [42 33 21]
  [34 12 45]]]


In [25]:
a[::2,:,1:2]

array([[[46],
        [48],
        [37]],

       [[45],
        [33],
        [12]]])

In [27]:
print(a)

[[[20 46 14]
  [47 48 35]
  [13 37 26]]

 [[31 41 34]
  [38 16 42]
  [22 21 19]]

 [[26 45 23]
  [42 33 21]
  [34 12 45]]]


In [29]:
a[:,:2,1:3]

array([[[46, 14],
        [48, 35]],

       [[41, 34],
        [16, 42]],

       [[45, 23],
        [33, 21]]])

In [31]:
a[::,:2:,1:3]

array([[[46, 14],
        [48, 35]],

       [[41, 34],
        [16, 42]],

       [[45, 23],
        [33, 21]]])

In [33]:
print(a)

[[[20 46 14]
  [47 48 35]
  [13 37 26]]

 [[31 41 34]
  [38 16 42]
  [22 21 19]]

 [[26 45 23]
  [42 33 21]
  [34 12 45]]]


In [35]:
a[::2,::2,0:1]

array([[[20],
        [13]],

       [[26],
        [34]]])

In [37]:
print(a)

[[[20 46 14]
  [47 48 35]
  [13 37 26]]

 [[31 41 34]
  [38 16 42]
  [22 21 19]]

 [[26 45 23]
  [42 33 21]
  [34 12 45]]]


In [39]:
a[::,::2,::2]

array([[[20, 14],
        [13, 26]],

       [[31, 34],
        [22, 19]],

       [[26, 23],
        [34, 45]]])