In [4]:
# indexing operation on 1-D array
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90])
print("content of a=",a)

content of a= [10 20 30 40 50 60 70 80 90]


In [6]:
#syntax for 1-D array Indexing
# 1dArray[index]

In [10]:
# get value 10 from a by using the positive indexing 
a[0]

10

In [12]:
# get value 10 from a with negative indexing
a[-len(a)]

10

In [14]:
# get last element from with positive indexing
a[len(a)-1]

90

In [16]:
# get last element with negative indexing
a[-1]

90

In [18]:
# get an element 50 from a 
a[4]

50

In [20]:
a[-5]

50

In [24]:
# indexing operation on 2-D Array
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90]).reshape(3,3)
print("content of a\n",a)

content of a
 [[10 20 30]
 [40 50 60]
 [70 80 90]]


In [26]:
# syntax for 2-D Array indexing
#syntax-1:2Darrayobj[rowindex,colindex]
         #or
# syntax-2:2Darrayobj[rowindex][colindex]

In [28]:
print(a)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [30]:
# get 50 with positive indexing 
a[1,1]

50

In [32]:
a[1][1]

50

In [34]:
# get 50 with negative indexing 
a[-2,-2]

50

In [36]:
a[-2][-2]

50

In [38]:
a[1,-2]

50

In [40]:
a[-2,1]

50

In [42]:
print(a)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [44]:
# get 90 from a 
a[2,2]

90

In [46]:
a[-1,-1]

90

In [48]:
a[2,-1]

90

In [50]:
a[-1,2]

90

In [52]:
a[2]

array([70, 80, 90])

In [54]:
# indexing operation on 3-D Array
import numpy as np
a=np.arange(3*3*3).reshape(3,3,3)
print("content of a\n",a)

content of a
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [56]:
# get first matrix
a[0]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [58]:
# get second matrix
a[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [60]:
# get second matrix
a[2]

array([[18, 19, 20],
       [21, 22, 23],
       [24, 25, 26]])

In [62]:
print(a)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [64]:
# get the element 14 from a
a[1][1][2]

14

In [66]:
a[-2][-2][-1]

14

In [68]:
a[1,-2,-1]

14

In [70]:
a[-2,1,2]

14

In [72]:
a[3,1,2]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [74]:
a[2]

array([[18, 19, 20],
       [21, 22, 23],
       [24, 25, 26]])

In [76]:
a[2,2,2]

26

In [78]:
# indexing operation on multi-dimension
import numpy as np
a=np.arange(2*3*3*3).reshape(2,3,3,3)
print("content of a=\n",a)

content of a=
 [[[[ 0  1  2]
   [ 3  4  5]
   [ 6  7  8]]

  [[ 9 10 11]
   [12 13 14]
   [15 16 17]]

  [[18 19 20]
   [21 22 23]
   [24 25 26]]]


 [[[27 28 29]
   [30 31 32]
   [33 34 35]]

  [[36 37 38]
   [39 40 41]
   [42 43 44]]

  [[45 46 47]
   [48 49 50]
   [51 52 53]]]]


In [80]:
# get first cluster 
a[0]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [82]:
# get second cluster 
a[1]

array([[[27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]],

       [[36, 37, 38],
        [39, 40, 41],
        [42, 43, 44]],

       [[45, 46, 47],
        [48, 49, 50],
        [51, 52, 53]]])

In [84]:
a[0][0]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [86]:
a[1]

array([[[27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]],

       [[36, 37, 38],
        [39, 40, 41],
        [42, 43, 44]],

       [[45, 46, 47],
        [48, 49, 50],
        [51, 52, 53]]])

In [88]:
a[1,1,1,1]

40

In [90]:
a[-1,-1,-1,-1]

53