## Advanced slicing operations  on 1-D

In [2]:
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90])
print("content of a={}".format(a))
print("dimension of a={}".format(a.ndim))

content of a=[10 20 30 40 50 60 70 80 90]
dimension of a=1


In [3]:
# get random values like 10 60 80 of 1-D

# step-1:identity the indices of 10 60 and 80---[0,5,7] or [-9,-4,-2]
# step-2:pass random elements indecies to 1-darray object ----ndarrayobj[[indices]]

In [4]:
# get random values like 10 60 80 of 1-D
#step-1
rind=[0,5,7]
# step-2
a[rind]

array([10, 60, 80])

In [5]:
# OR
# step-1
rind=[-9,-4,-2]
# step-2
a[rind]

array([10, 60, 80])

In [6]:
# OR 
a[[0,5,7]]

array([10, 60, 80])

In [7]:
# OR 
a[[-9,-4,-2]]

array([10, 60, 80])

In [8]:
print(a)

[10 20 30 40 50 60 70 80 90]


In [9]:
a[[1,-2,1]]

array([20, 80, 20])

In [10]:
x=np.array([1,-2,1])
a[x]

array([20, 80, 20])

## Advanced slicing operation on 2-D slicing

In [21]:
a=np.array([10,20,30,40,50,60,70,80,90]).reshape(3,3)
print("content of a\n",a)
print("dimension of a=",a.ndim)

content of a
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
dimension of a= 2


In [23]:
# get the principle diagnol elements 10 50 90
rind=(0,1,2) # here rind presents the row indices
cind=(0,1,2) # here cind presents the column indices
a[rind,cind]

array([10, 50, 90])

In [27]:
a[(0,1,2),(0,1,2)]

array([10, 50, 90])

In [29]:
a[[0,1,2],[0,1,2]]

array([10, 50, 90])

In [31]:
a[(0,1,2),[0,1,2]]

array([10, 50, 90])

In [33]:
print(a)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [37]:
# get the values of 30 50 70 the principle diagonal elements in reverse order
# row indecies for values of 30 50 70
rind=(0,1,2)
# column indecies for values of 30 50 70
cind=[2,1,0]
# pass the values to the ndarrat object 
a[rind,cind]

array([30, 50, 70])

In [39]:
print(a)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [41]:
# get the elements of 10 40 60 90 
a[(0,1,1,2),(0,0,2,2)]

array([10, 40, 60, 90])

In [43]:
# get the elmens of 10 60 70
a[(0,1,2),(0,2,0)]

array([10, 60, 70])

In [45]:
# get the elmens of 10 60 70 with -ve indexing 
a[(-3,-2,-1),[-3,-1,-3]]

array([10, 60, 70])

## Advanced slicing operation on 3-D 

In [49]:
a=np.arange(27).reshape(3,3,3)
print("content of a\n",a)

content of a
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [51]:
# get the elements of 4 12 26
# matrics indices of 4 12 26
mind=(0,1,2)
# row indices of 4 12 26
rind=(1,1,2)
# matrics indices of 4 12 26
cind=(1,0,2)
# pass the values to the ndarray object
a[mind,rind,cind]

array([ 4, 12, 26])

In [53]:
a[(0,1,2),(1,1,2),(1,0,2)]

array([ 4, 12, 26])

In [55]:
print(a)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [57]:
# get 0 4 8 20 22 24
a[(0,0,0,2,2,2),(0,1,2,0,1,2),(0,1,2,2,1,0)]

array([ 0,  4,  8, 20, 22, 24])

In [59]:
print(a)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [61]:
a[[-3,-3,-3,-1,-1,-1],[-3,-2,-1,-3,-2,-1],[-3,-2,-1,-1,-2,-3]]

array([ 0,  4,  8, 20, 22, 24])