## ones()

In [3]:
import numpy as np
a=np.ones(10)
print(a)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [5]:
a=np.ones(10,int)
print(a)

[1 1 1 1 1 1 1 1 1 1]


In [7]:
a=np.ones((3,3),int)

In [9]:
print(a)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [11]:
a=np.ones((2,3,3),int)
print(a)

[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


## full()

In [15]:
# syntax: varname=numpy.full(shape,fill_value,dtype)

In [9]:
import numpy as np
a=np.full(5,10)

In [11]:
print(a)

[10 10 10 10 10]


In [13]:
a=np.full(5,10,float)
print(a)

[10. 10. 10. 10. 10.]


In [15]:
a=np.full((2,3),20)
print(a)

[[20 20 20]
 [20 20 20]]


In [17]:
a=np.full((3,3,3),2,float)
print(a)

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


In [21]:
a=np.full((2,3),fill_value=5,dtype=int)
print(a)

[[5 5 5]
 [5 5 5]]


## identity()

In [25]:
# syntax:varname=numpy.identity(N,dtype) 

In [31]:
import numpy as np
a=np.identity(3)

In [33]:
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [35]:
a=np.identity(2)
print(a)

[[1. 0.]
 [0. 1.]]


In [37]:
a=np.identity(4,int)
print(a)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


## linspace()

In [40]:
# syntax:varname=numpy.linspace(start,stop,num,endpoint,retstep,dtype)

In [42]:
import numpy as np
a=np.linspace(1,10)

In [44]:
print(a)

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]


In [46]:
a=np.linspace(1,5,num=10)

In [48]:
print(a)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [54]:
a=np.linspace(1,20,num=5,endpoint=True)
print(a)

[ 1.    5.75 10.5  15.25 20.  ]


In [56]:
a=np.linspace(1,20,num=5,endpoint=False)

In [58]:
print(a)

[ 1.   4.8  8.6 12.4 16.2]


In [74]:
a=np.linspace(10,50,num=20,retstep=False)
print(a)

[10.         12.10526316 14.21052632 16.31578947 18.42105263 20.52631579
 22.63157895 24.73684211 26.84210526 28.94736842 31.05263158 33.15789474
 35.26315789 37.36842105 39.47368421 41.57894737 43.68421053 45.78947368
 47.89473684 50.        ]


In [76]:
a,rs=np.linspace(10,50,num=20,retstep=True)
print(a)
print(rs)

[10.         12.10526316 14.21052632 16.31578947 18.42105263 20.52631579
 22.63157895 24.73684211 26.84210526 28.94736842 31.05263158 33.15789474
 35.26315789 37.36842105 39.47368421 41.57894737 43.68421053 45.78947368
 47.89473684 50.        ]
2.1052631578947367


In [84]:
a,rs=np.linspace(1,15,num=15,endpoint=True,retstep=True,dtype=int)
print(a)
print(rs)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
1.0
