## 1.randint()

In [3]:
# create an object of ndarray by using the randint()

In [5]:
# syntax: varname=numpy.random.randint(value)

In [7]:
import numpy as np

In [9]:
x=np.random.randint(10)
print(x,type(x))

3 <class 'int'>


In [13]:
x=np.random.randint(10)
print(x,type(x))

2 <class 'int'>


In [15]:
x=np.random.randint(10)
print(x,type(x))

0 <class 'int'>


In [17]:
x=np.random.randint(10)
print(x,type(x))

4 <class 'int'>


In [21]:
x=np.random.randint(10)
print(x,type(x))

7 <class 'int'>


In [23]:
x=np.random.randint(10)
print(x,type(x))

7 <class 'int'>


In [25]:
x=np.random.randint(10)
print(x,type(x))

3 <class 'int'>


In [27]:
# synatax2: varname=numpy.random.randint(low,high)

In [29]:
x=np.random.randint(100,200)
print(x,type(x))

124 <class 'int'>


In [31]:
x=np.random.randint(100,200)
print(x,type(x))

137 <class 'int'>


In [35]:
x=np.random.randint(100,200)
print(x,type(x))

155 <class 'int'>


In [39]:
x=np.random.randint(100,200)
print(x,type(x))

167 <class 'int'>


In [41]:
x=np.random.randint(1000,10000)
print(x,type(x))

4956 <class 'int'>


In [43]:
x=np.random.randint(10000,100000)
print(x,type(x))

23841 <class 'int'>


In [45]:
for i in range(11):
    x=np.random.randint(1000,10000)
    print(x,type(x))

9341 <class 'int'>
3533 <class 'int'>
4884 <class 'int'>
7436 <class 'int'>
5087 <class 'int'>
6269 <class 'int'>
7487 <class 'int'>
6717 <class 'int'>
4181 <class 'int'>
4209 <class 'int'>
6245 <class 'int'>


In [47]:
for i in range(10):
    x=np.random.randint(100)
    print(x,type(x))

7 <class 'int'>
66 <class 'int'>
88 <class 'int'>
88 <class 'int'>
30 <class 'int'>
71 <class 'int'>
82 <class 'int'>
97 <class 'int'>
79 <class 'int'>
13 <class 'int'>


In [58]:
for i in range(10):
    x=np.random.randint(10000,100000)
    print("G-",x,type(x))

G- 35309 <class 'int'>
G- 44318 <class 'int'>
G- 89901 <class 'int'>
G- 85934 <class 'int'>
G- 98280 <class 'int'>
G- 33905 <class 'int'>
G- 25212 <class 'int'>
G- 73946 <class 'int'>
G- 37514 <class 'int'>
G- 98175 <class 'int'>


In [53]:
# syntax-3: varname=numpy.random.randint(low,high,size)

In [60]:
x=np.random.randint(10,21,size=4)
print(x,type(x))

[19 18 13 13] <class 'numpy.ndarray'>


In [62]:
x=np.random.randint(10,21,size=3)
print(x,type(x))

[17 17 11] <class 'numpy.ndarray'>


In [68]:
for i in range(10):
    x=np.random.randint(10,20,size=4)
    print(i,")",x,type(x))

0 ) [16 16 19 15] <class 'numpy.ndarray'>
1 ) [16 11 11 18] <class 'numpy.ndarray'>
2 ) [13 13 12 15] <class 'numpy.ndarray'>
3 ) [17 13 17 13] <class 'numpy.ndarray'>
4 ) [12 14 15 18] <class 'numpy.ndarray'>
5 ) [12 10 14 15] <class 'numpy.ndarray'>
6 ) [10 19 19 19] <class 'numpy.ndarray'>
7 ) [10 14 18 11] <class 'numpy.ndarray'>
8 ) [15 18 12 17] <class 'numpy.ndarray'>
9 ) [16 18 18 15] <class 'numpy.ndarray'>


In [70]:
x=np.random.randint(10,100,size=(3,4))
print(x,type(x))

[[75 73 26 84]
 [76 71 54 66]
 [29 22 59 61]] <class 'numpy.ndarray'>


In [74]:
for i in range(1,10):
    x=np.random.randint(100,1000,size=(3,3))
    print(x,type(x))
    print("-------------------------")

[[790 743 921]
 [251 223 189]
 [851 759 636]] <class 'numpy.ndarray'>
-------------------------
[[815 368 721]
 [899 668 442]
 [848 238 970]] <class 'numpy.ndarray'>
-------------------------
[[508 156 391]
 [567 478 205]
 [321 380 488]] <class 'numpy.ndarray'>
-------------------------
[[175 646 147]
 [564 980 750]
 [899 462 657]] <class 'numpy.ndarray'>
-------------------------
[[327 933 901]
 [569 755 856]
 [189 447 747]] <class 'numpy.ndarray'>
-------------------------
[[188 609 753]
 [769 675 470]
 [914 787 359]] <class 'numpy.ndarray'>
-------------------------
[[994 526 184]
 [229 486 983]
 [931 998 853]] <class 'numpy.ndarray'>
-------------------------
[[747 137 622]
 [575 728 167]
 [873 548 878]] <class 'numpy.ndarray'>
-------------------------
[[871 559 996]
 [301 892 439]
 [637 956 978]] <class 'numpy.ndarray'>
-------------------------


In [78]:
x=np.random.randint(10,100,size=(3,3,3))
print(x,type(x))

[[[49 63 58]
  [85 76 87]
  [34 62 56]]

 [[51 48 86]
  [97 56 28]
  [82 45 40]]

 [[98 73 97]
  [22 93 60]
  [78 30 80]]] <class 'numpy.ndarray'>


In [86]:
for i in range(1,6):
    x=np.random.randint(1000,10000,size=(2,3,2))
    print(i,x,type(x))
    print("="*50)

1 [[[9741 8186]
  [7900 2035]
  [6643 2999]]

 [[1434 3358]
  [3756 7623]
  [2659 6275]]] <class 'numpy.ndarray'>
2 [[[8248 5413]
  [5897 9665]
  [8035 3553]]

 [[4213 1878]
  [7361 7777]
  [1390 5462]]] <class 'numpy.ndarray'>
3 [[[4732 6710]
  [8811 4708]
  [2189 3486]]

 [[1370 5906]
  [5644 4433]
  [6522 3911]]] <class 'numpy.ndarray'>
4 [[[1850 3718]
  [4718 4070]
  [3390 4935]]

 [[8383 8351]
  [3802 9190]
  [6508 1955]]] <class 'numpy.ndarray'>
5 [[[4573 7217]
  [4328 8593]
  [8139 2914]]

 [[5267 6729]
  [5550 9091]
  [8118 2550]]] <class 'numpy.ndarray'>


## rand()

In [91]:
# create an object of ndarray by using rand()

In [93]:
# syntax: numpy.random.rand()

In [95]:
import numpy as np

In [97]:
a=np.random.rand()

In [99]:
print(a,type(a))

0.23088388626241385 <class 'float'>


In [101]:
a=np.random.rand()
print(a,type(a))

0.26654274880447026 <class 'float'>


In [103]:
a=np.random.rand()
print(a,type(a))

0.026233554410042048 <class 'float'>


In [105]:
for i in range(1,5):
    a=np.random.rand()
    print(a,type(a))

0.8169105063355123 <class 'float'>
0.25406379916790967 <class 'float'>
0.24042223974680388 <class 'float'>
0.6745486552518214 <class 'float'>


In [107]:
for i in range(5):
    a=np.random.rand()
    print("%0.2f" %a)

0.96
0.85
0.38
0.02
0.58


In [117]:
for i in range(5):
    a=np.random.rand()
    print(round(a,2),type(a))

0.41 <class 'float'>
0.9 <class 'float'>
0.71 <class 'float'>
0.31 <class 'float'>
0.73 <class 'float'>


In [135]:
# syntax2: varname=numpy.random.rand(value)

In [137]:
a=np.random.rand(4)
print(a,type(a))

[0.55152808 0.98033238 0.5894722  0.05440658] <class 'numpy.ndarray'>


In [139]:
a=np.random.rand(5)
print(a,type(a))

[0.36376602 0.81239352 0.22901995 0.9924943  0.63155717] <class 'numpy.ndarray'>


In [141]:
# syntax3: varname=numpy.random.rand(rows,cols)

In [147]:
a=np.random.rand(1,5)
print(a,type(a))
print("dimension=",a.ndim)

[[0.34162749 0.20041014 0.1179666  0.90464682 0.23977262]] <class 'numpy.ndarray'>
dimension= 2


In [149]:
# syntax4: varname=numpy.random.rand(no.of.matrices,rows,cols)

In [151]:
a=np.random.rand(2,3,3)
print(a,type(a))
print("Dimension of a=",a.ndim)

[[[0.11108171 0.80120054 0.60019055]
  [0.8714855  0.05467902 0.36619045]
  [0.71444566 0.80166076 0.76751299]]

 [[0.24550483 0.45764826 0.75515312]
  [0.54200104 0.60898267 0.08570937]
  [0.10310756 0.41992585 0.566998  ]]] <class 'numpy.ndarray'>
Dimension of a= 3


## uniform()

In [154]:
a=np.random.uniform()
print(a,type(a))

0.6127450808366831 <class 'float'>


In [157]:
a=np.random.uniform()
print(a,type(a))

0.6451062069123845 <class 'float'>


In [159]:
a=np.random.uniform()
print(a,type(a))

0.7393319437439484 <class 'float'>


In [161]:
# syntax2: varname=numpy.random.uniform(low,high)

In [163]:
a=np.random.uniform(1.2,5.6)
print(a,type(a))

3.1019438580469725 <class 'float'>


In [165]:
for i in range(10):
    a=np.random.uniform(1.5,5.6)
    print(a,type(a))

4.163910584987369 <class 'float'>
1.569377076280237 <class 'float'>
2.6085476767449025 <class 'float'>
3.4959873427562074 <class 'float'>
4.769669890089785 <class 'float'>
1.8008110487552038 <class 'float'>
4.522548796609253 <class 'float'>
2.0207012671543665 <class 'float'>
4.57949922926511 <class 'float'>
3.3557484375867697 <class 'float'>


In [167]:
for i in range(5):
    a=np.random.uniform(1.5,2.5)
    print(a,type(a))

1.860853386141697 <class 'float'>
1.6829216070666768 <class 'float'>
1.7604650307644778 <class 'float'>
2.3903018817712782 <class 'float'>
2.052107945890765 <class 'float'>


In [169]:
# syntax: varname=numpy.random.uniform(low,high,size)

In [171]:
a=np.random.uniform(10,12,4)
print(a,type(a))

[11.85047822 10.93923417 10.66949043 10.07480207] <class 'numpy.ndarray'>


In [173]:
for i in range(5):
    a=np.random.uniform(10,13,5)
    print(a,type(a))

[12.27190773 10.78598568 12.29058549 11.40132489 11.19085975] <class 'numpy.ndarray'>
[10.50076715 12.74105081 11.68817364 10.12127925 11.26869954] <class 'numpy.ndarray'>
[11.15480879 12.93305346 12.7766624  11.53568793 12.82175429] <class 'numpy.ndarray'>
[12.9926041  12.4364117  10.92566632 11.11576635 10.91189309] <class 'numpy.ndarray'>
[10.95633276 12.4947708  11.13122001 12.32350692 12.2079369 ] <class 'numpy.ndarray'>


In [175]:
a=np.random.uniform(10,20,size=(3,3))
print(a,type(a))

[[19.41114608 14.85920693 10.38526397]
 [10.06902906 15.10971512 17.07483287]
 [12.11365403 14.52567578 17.98383368]] <class 'numpy.ndarray'>


In [177]:
a=np.random.uniform(10,15,(2,3,3))
print(a,type(a))

[[[12.89361974 10.03245316 11.04737776]
  [13.73109586 11.93142321 13.19943949]
  [14.12351812 10.59779875 13.48508527]]

 [[14.85903869 11.4369465  13.39771269]
  [11.59923649 10.80579992 14.75963199]
  [10.9028339  12.03932299 13.97433158]]] <class 'numpy.ndarray'>
