## 21 st sep,2024

## randn()

In [5]:
# creating an ndarray object by using the randn() 

In [6]:
import numpy as np
a=np.random.randn()
print(a,type(a))

0.5196976447100011 <class 'float'>


In [7]:
a=np.random.randn()
print(a,type(a))

0.46729729199776054 <class 'float'>


In [8]:
a=np.random.randn()
print(a,type(a))

0.8047651551991192 <class 'float'>


In [9]:
a=np.random.randn()
print(a,type(a))

-0.5682246997474585 <class 'float'>


In [10]:
a=np.random.randn()
print(a,type(a))

0.3972662414225861 <class 'float'>


In [11]:
a=np.random.randn()
print(a,type(a))

-0.19795338812919755 <class 'float'>


In [12]:
a=np.random.randn()
print(a,type(a))

0.323401246178334 <class 'float'>


In [13]:
for i in range(1,6):
    a=np.random.randn()
    print(a,type(a))

0.24407839374992935 <class 'float'>
-0.722101846159214 <class 'float'>
-0.45447279021720116 <class 'float'>
-0.740126660589188 <class 'float'>
0.13812846988177585 <class 'float'>


In [14]:
for i in range(1,6):
    a=np.random.randn()
    print(a,type(a))

0.33078318141188384 <class 'float'>
-0.7719348954134463 <class 'float'>
-0.15636025514140975 <class 'float'>
0.09399278436781555 <class 'float'>
0.3365791214039929 <class 'float'>


In [15]:
# syntax:varname=numpy.random.randn(value) creating 1-D array

In [16]:
a=np.random.randn(5)
print(a,type(a))

[ 1.34619618  0.50969829  0.34824214  1.07689987 -0.87908683] <class 'numpy.ndarray'>


In [17]:
a=np.random.randn(10)
print(a,type(a))

[-0.32878284  0.49870243  0.04173637  0.86093362  0.95587398  0.43651457
  0.13899767  0.80672062  0.48871706  0.24392652] <class 'numpy.ndarray'>


In [18]:
for i in range(5):
    a=np.random.randn(5)
    print(a,type(a))

[ 1.47447069 -1.40446768 -0.63162151 -0.29111588  0.22676332] <class 'numpy.ndarray'>
[-1.70329631  0.42835246 -2.25008447 -0.57079148  0.18736272] <class 'numpy.ndarray'>
[-0.27138969  0.29660864 -0.43932376 -0.97152143  0.67938701] <class 'numpy.ndarray'>
[ 1.28339893 -0.00798536 -0.88991259  0.52693244  0.09181578] <class 'numpy.ndarray'>
[-1.73345203 -0.12925494 -0.52624056  0.49795279 -0.30175703] <class 'numpy.ndarray'>


In [19]:
# syntax3: varname=numpy.random.randn(row,col)

In [20]:
a=np.random.randn(2,3)
print(a,type(a))

[[ 0.61322136 -0.88297018  0.72876789]
 [ 1.63630297 -0.29709876  0.84530719]] <class 'numpy.ndarray'>


In [21]:
a=np.random.randn(10,10)
print(a,type(a))

[[ 0.1392871   0.00282993 -1.4063786  -0.75751259 -0.81609356  1.07437928
  -1.48147739  0.04020376  0.13601362  0.64480765]
 [-0.19607293 -1.11276423  0.51466589  0.97601979 -0.02836339 -1.12800678
   0.21875013  0.55791858 -1.54578478 -0.67168717]
 [-1.21405435  2.34253728 -1.10781937 -0.51498382  2.0378501  -0.18389541
   0.31147936 -1.02144033  0.11897789  0.7006776 ]
 [ 0.13632854  1.48260937  1.06849673 -1.36493305  1.39697675 -0.8103427
   0.16334839 -2.30779497 -0.84719322 -0.23316662]
 [ 0.37940005 -1.32595316  1.3124058  -0.49514233 -0.6645011   0.07020302
   1.12798213  1.38725855 -0.23461186  1.14658003]
 [-0.05623037  0.28357875  1.6158535  -0.90549137  1.14352614  1.74979488
   0.58863344 -1.30407513 -2.29477821 -1.12238552]
 [ 0.06934979 -0.15550872  0.62741324 -0.47796914  2.46626005  0.70050681
   0.63481652 -0.79572712  0.37883865 -0.43250852]
 [-1.42812109  0.92446968  0.40684976  0.27567428 -0.25955772  0.04907836
   0.83766363 -1.01623279 -0.29026005  0.05134989]
 

In [22]:
for i in range(10):
    a=np.random.randn(2,3)
    print(a,type(a))

[[-1.18140439 -1.09685431 -1.10110722]
 [-0.31970834  0.14164447 -2.05631932]] <class 'numpy.ndarray'>
[[-0.47242424 -0.37658093  1.29887161]
 [-1.23522894 -1.07131332 -1.63611142]] <class 'numpy.ndarray'>
[[-0.01023692 -0.77974804  0.71770454]
 [-1.08504274 -0.77897539 -1.25682876]] <class 'numpy.ndarray'>
[[-0.28341506  1.13962153  0.84959123]
 [-1.26882546  0.57434492  1.00429685]] <class 'numpy.ndarray'>
[[-0.94219549 -0.05728447 -0.77991689]
 [ 0.40243497 -1.2506444  -1.42525975]] <class 'numpy.ndarray'>
[[1.04976909 0.37963665 0.72565351]
 [0.3249977  1.34143481 2.14902547]] <class 'numpy.ndarray'>
[[ 0.60687962 -1.78713152  1.57196823]
 [-0.57056068  1.06034806 -0.90246095]] <class 'numpy.ndarray'>
[[-0.69936946  0.73324967  0.69947361]
 [-1.56122469  0.33805922  0.41681973]] <class 'numpy.ndarray'>
[[ 0.4882641  -1.92012784 -0.42509379]
 [ 0.4750035   0.51532291  0.62796695]] <class 'numpy.ndarray'>
[[ 0.16067886 -0.91339315  0.98536975]
 [-0.68177695 -0.23601325  0.49636921]] 

In [23]:
# syntax4: varname=numpy.random.randn(no.of.matrises,rows,cols)

In [24]:
a=np.random.randn(2,3,3)
print(a,type(a))

[[[-0.97020889  1.28926393  1.09276022]
  [-0.08144377  1.26588096 -0.19085694]
  [ 0.05765488 -1.35198442  1.36971101]]

 [[ 0.60131495 -0.08768402  0.82687022]
  [ 0.3656855   2.07043405  0.71065373]
  [ 1.28480544  0.80934579  1.03132449]]] <class 'numpy.ndarray'>


In [25]:
a=np.random.randn(3,3,3)
print(a,type(a))

[[[-0.18815682  0.88389832 -0.35327113]
  [ 0.44769041 -1.02475868  0.05023997]
  [-1.60845731  0.14752712  0.84270599]]

 [[ 1.86173918 -1.03955954  0.81828551]
  [ 0.44099431  1.03567314  0.83758188]
  [-0.80958127  0.0580189  -0.15495812]]

 [[-1.28298691 -1.48389193  1.29588106]
  [-0.60565437 -0.20392781 -0.1893594 ]
  [-0.65748592  1.19409397 -1.78307028]]] <class 'numpy.ndarray'>


## shuffle()

In [27]:
a=np.arange(10)
print(a,type(a),id(a))
print("------------------------")
np.random.shuffle(a)
print(a,type(a))

[0 1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'> 2196477298512
------------------------
[9 3 8 2 7 0 4 5 6 1] <class 'numpy.ndarray'>


In [28]:
np.random.shuffle(a)
print(a,type(a))

[6 8 4 5 0 3 9 2 1 7] <class 'numpy.ndarray'>


In [29]:
np.random.shuffle(a)
print(a,type(a))

[6 7 5 0 8 4 3 9 1 2] <class 'numpy.ndarray'>


In [30]:
a=np.random.randint(10,21,size=(2,5))
print(a,type(a))

[[19 20 18 13 13]
 [15 11 15 20 15]] <class 'numpy.ndarray'>


In [31]:
np.random.shuffle(a)
print(a,type(a))

[[15 11 15 20 15]
 [19 20 18 13 13]] <class 'numpy.ndarray'>


In [32]:
np.random.shuffle(a)
print(a,type(a))

[[19 20 18 13 13]
 [15 11 15 20 15]] <class 'numpy.ndarray'>


In [33]:
a=np.arange(48).reshape(3,4,4)
print(a,type(a))

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]

 [[32 33 34 35]
  [36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]] <class 'numpy.ndarray'>


In [34]:
np.random.shuffle(a)
print(a,type(a))

[[[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]

 [[32 33 34 35]
  [36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]

 [[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]] <class 'numpy.ndarray'>


In [35]:
np.random.shuffle(a)
print(a,type(a))

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[32 33 34 35]
  [36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]] <class 'numpy.ndarray'>


In [36]:
x=np.arange(48).reshape(2,3,4,2)
print(x,type(x))

[[[[ 0  1]
   [ 2  3]
   [ 4  5]
   [ 6  7]]

  [[ 8  9]
   [10 11]
   [12 13]
   [14 15]]

  [[16 17]
   [18 19]
   [20 21]
   [22 23]]]


 [[[24 25]
   [26 27]
   [28 29]
   [30 31]]

  [[32 33]
   [34 35]
   [36 37]
   [38 39]]

  [[40 41]
   [42 43]
   [44 45]
   [46 47]]]] <class 'numpy.ndarray'>


In [37]:
np.random.shuffle(x)
print(x,type(x))

[[[[ 0  1]
   [ 2  3]
   [ 4  5]
   [ 6  7]]

  [[ 8  9]
   [10 11]
   [12 13]
   [14 15]]

  [[16 17]
   [18 19]
   [20 21]
   [22 23]]]


 [[[24 25]
   [26 27]
   [28 29]
   [30 31]]

  [[32 33]
   [34 35]
   [36 37]
   [38 39]]

  [[40 41]
   [42 43]
   [44 45]
   [46 47]]]] <class 'numpy.ndarray'>


## choice()

In [39]:
a=np.array([10,20,30,40,50,60,70,80,90])
print(a,type(a))
print("--------------------------------------")
x=np.random.choice(a)
print(x)

[10 20 30 40 50 60 70 80 90] <class 'numpy.ndarray'>
--------------------------------------
20


In [40]:
x=np.random.choice(a)
print(x)

40


In [41]:
x=np.random.choice(a)
print(x)

20


In [45]:
s="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0987654321"
a=np.array(list(s))
for i in range(1,11):
    x=np.random.choice(a,size=5)
    print("".join(x))

UjYB5
kjpHs
1TbZX
SWhPW
VL2Lk
8ryDx
1bB30
LssVc
2CbnT
ZuW6k


In [221]:
s="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0987654321"
a=np.array(list(s))
for i in range(1,11):
    x=np.random.choice(a,size=5)
    print("".join(x))

eTJNA
E3VBk
sj9FB
l4327
hhFI2
vbE9L
e2hXH
nPJH6
QwshM
F0Vq9


In [223]:
state=["AP","TG","MH","UD","TN","KN"]
rtacode=[39,18,22,56,67,13]
s="ABCDEFGHIJKLMNOPQRSTUVWXYZ"
st=np.array(state)
r=np.array(rtacode)
a=np.array(list(s))
for i in range(1,21):
    j=np.random.choice(st)
    k=np.random.choice(r)
    l=np.random.choice(a,size=2)
    m=np.random.randint(1000,10000)
    print(j,k,"".join(l),m)

TG 67 VO 8907
UD 18 ZZ 1351
UD 22 KH 8325
KN 67 CM 5042
UD 39 UL 5416
MH 22 LF 1212
TG 67 CD 5092
AP 39 NH 9341
TN 13 GM 3543
TG 13 BJ 5132
TN 67 CB 3748
TG 56 JQ 4485
KN 56 LS 9472
KN 22 EH 9765
TN 39 ES 4211
AP 67 MR 4380
MH 56 YU 4920
MH 67 JU 3481
MH 18 AC 5224
UD 18 TG 1567
